### ISSUE TITLE
paleta de color centrada en naranjo

### ISSUE THREAD

**Issue by pdaire** [lets-talk/homepage#1]
los otros colores tienen que ser coherentes con el naranjo. ¿quizas tonos de naranjo?

**Comment by camargozzini** [comment]
a que otro color te refieres? sólo hay naranjo, blanco y gris? quieres que ponga más naranjo?

**Comment by pdaire** [comment]
antes había unos calipsos en el `nav`. no, no más naranjo por favor no más :grimacing:

**Comment by camargozzini** [comment]
jajajaja menos naranjo? jaja
