### ISSUE TITLE
falta una seccion de contact us

### ISSUE THREAD

**Issue by pdaire** [lets-talk/homepage#4]

**Comment by pdaire** [comment]
un formulario de google doc para las empresas que se quieren contratar el servicio:

me gusta el formato del de [abrelatam](http://2015.abrelatam.org/#subscribe) en vez de país un dropwon para categorías:
- Telecomunaciones
- Finanzas
- Slaud
- Entretenimiento
- Viajes

**Comment by camargozzini** [comment]
Crea el form plis y me lo mandas (no quiero que quede con mi mail)

**Comment by pdaire** [comment]
este
https://docs.google.com/a/letsta.lk/forms/d/1qqXojp9ldvojcTAEgwrw070qV-ecZlpQR3E5jgtho-E/viewform
